### ISSUE TITLE
An `image2text` overfitting test performs overfitting but the `eval_bleu` appears as `0.0.`

### ISSUE THREAD

**Issue by GerrySant** [GerrySant/multimodalhugs#21]
An `image2text` overfitting test performs overfitting but the `eval_bleu` appears as `0.0.`

Details:

- Code:

```
export CONFIG_PATH='/home/gsantm/scripts/multimodalhugs/experiments/hebrew/config.yaml'
export OUTPUT_PATH="/home/gsantm/store/multimodalhugs_experiments/debbug_byt5"

export CUDA_VISIBLE_DEVICES=0 #,2,3

#rm -rf $OUTPUT_PATH
python /home/gsantm/repositories/multimodalhugs/multimodalhugs/multimodalhugs_cli/training_setup.py --modality "image2text" --config_path $CONFIG_PATH

# ----------------------------------------------------------
# 4. Train the Model
# ----------------------------------------------------------

multimodalhugs-train --task "translation" \
    --config_path $CONFIG_PATH \
    --output_dir $OUTPUT_PATH \
    --visualize_prediction_prob 1 \
    --report_to none
```

- Config:

```
model:
  type: multimodal_embedder
  feature_extractor_type: clip
  pretrained_feature_extractor: openai/clip-vit-base-patch32
  multimodal_mapper_type: linear
  multimodal_mapper_layer_norm_before: true
  multimodal_mapper_dropout: 0.1
  backbone_type: t5 # t5
  pretrained_backbone: google/t5-efficient-tiny # google/byt5-small / google-t5/t5-base
  feat_dim: 512
  freeze_backbone: false
  freeze_decoder_embed_tokens: false
  freeze_encoder_embed_tokens: false
  freeze_lm_head: false
  max_length: 10
  feature_extractor_cfg: # Specify args to be changes in the feature extractor arquitecture
    feature_extractor_argumnets: whatever

training:
  run_name: debbug_byt5
  output_dir: /home/gsantm/store/multimodalhugs_experiments/debbug_byt5
  do_train: true
  do_eval: true
  logging_strategy: steps           # Log once per epoch
  eval_strategy: steps       # Evaluate once per epoch
  eval_steps: 50
  save_strategy: steps                           # Checkpoint save strategy during training.
  save_steps: 20000000                                  # Interval (in steps) at which model checkpoints are saved.
  logging_steps: 10                               # Interval (in steps) at which training metrics are logged.
  #eval_strategy: steps
  #max_steps: 200000
  num_train_epochs: 15000
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 8
  save_total_limit: 2
  learning_rate: 5e-05
  max_grad_norm: 0.0
  overwrite_output_dir: true
  predict_with_generate: true
  metric_for_best_model: bleu
  load_best_model_at_end: true
  seed: 3435
  fp16: false

data:
  train_metadata_file:
    /home/gsantm/scripts/multimodalhugs/experiments/hebrew/other_files/metadata_train_toy.tsv                    # /home/gsantm/store/demo_multimodalhugs/metadata/metadata_train.tsv
  validation_metadata_file:
    /home/gsantm/scripts/multimodalhugs/experiments/hebrew/other_files/metadata_train_toy.tsv                         # /home/gsantm/store/demo_multimodalhugs/metadata/metadata_dev.tsv
  test_metadata_file:
    /home/gsantm/scripts/multimodalhugs/experiments/hebrew/other_files/metadata_train_toy.tsv                   # /home/gsantm/store/demo_multimodalhugs/metadata/metadata_test.tsv
  font_path:
    /home/gsantm/repositories/multimodalhugs/examples/multimodal_translation/image2text_translation/other/Arial.ttf
  text_tokenizer_path: google/t5-efficient-tiny
  preprocess:
    width: 224
    height: 224
    channels: 3
    dataset_mean: '[0.9819646859188279, 0.9819646859188279, 0.9819646859188279]'
    dataset_std: '[0.12833405937294548, 0.12833405937294548, 0.12833405937294548]'

```

- Output:

```
T - a</s><pad><pad><pad><pad><pad><pad><pad>
L - a
P - <pad> a</s><pad><pad><pad><pad><pad><pad>
H - a

T - b</s><pad><pad><pad><pad><pad><pad><pad>
L - b
P - <pad> b</s><pad><pad><pad><pad><pad><pad>
H - b

T - cd</s><pad><pad><pad><pad><pad><pad>
L - cd
P - <pad> cd</s><pad><pad><pad><pad><pad>
H - cd

T - ef</s><pad><pad><pad><pad><pad><pad>
L - ef
P - <pad> ef</s><pad><pad><pad><pad><pad>
H - ef
{'eval_loss': 6.752178705937695e-06, 'eval_bleu': 0.0, 'eval_gen_len': 3.5, 'eval_runtime': 0.399, 'eval_samples_per_second': 40.105, 'eval_steps_per_second': 5.013, 'epoch': 2250.0}
```
