### ISSUE TITLE
Config should not be overwritten

### ISSUE THREAD

**Issue by AmitMY** [GerrySant/multimodalhugs#26]
Right now, when running setup, the config file is edited. Various parameters are added and changed, and it is not easy to work with, especially with git.

I'd like the original config file to remain, while a new config file can be modified. But when I work on my project, I don't want my source file to change.

**Comment by AmitMY** [comment]
Another idea, if you really do have to update the config file, would be to add a new field: `automatic` where everything goes under, for example:
```yaml
automatic:
  model: 
     d_model: 1472
    pad_token_id: 0
    bos_token_id:
    eos_token_id: 1
    decoder_start_token_id: 0
    model_name_or_path:
    /scratch/amoryo/tmp/signwriting-transcription/results/signwriting_transcription_model/trained_model
```

Then the training script will deep-merge the automatic and normal, but at least it would be clear to see what is manually set up and what is automatic
